### ISSUE TITLE
EXCEPTION _send_to_openai.<locals>.send_to_openai() got an unexpected keyword argument 'stream'

### ISSUE THREAD

**Issue by raohemanth** [plasma-umass/ChatDBG#10]
Unable to execute this program. Can you help me?

```
(venv) ghost:testLLMDebugging hemanth$ chatdbg -c continue executeProgram.py
Traceback (most recent call last):
  File "/Users/hemanth/Documents/work/plv/testLLMDebugging/venv/lib/python3.11/site-packages/chatdbg/chatdbg.py", line 77, in main
    pdb._run(target)
  File "/Users/hemanth/Documents/work/plv/testLLMDebugging/venv/lib/python3.11/site-packages/chatdbg/pdb.py", line 1643, in _run
    self.run(target.code)
  File "/Users/hemanth/.pyenv/versions/3.11.4/lib/python3.11/bdb.py", line 600, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/hemanth/Documents/work/plv/testLLMDebugging/executeProgram.py", line 9, in <module>
    print(tryme(100))
          ^^^^^^^^^^
  File "/Users/hemanth/Documents/work/plv/testLLMDebugging/executeProgram.py", line 4, in tryme
    if x / i > 2:
       ~~^~~
ZeroDivisionError: division by zero
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Users/hemanth/Documents/work/plv/testLLMDebugging/executeProgram.py(4)tryme()
-> if x / i > 2:
(ChatDBG Pdb) why
EXCEPTION _send_to_openai.<locals>.send_to_openai() got an unexpected keyword argument 'stream'
```

**Comment by emeryberger** [comment]
Thanks for the report! This has been fixed. I will push a new release momentarily.
