### ISSUE TITLE
ImportError: cannot import name '_ModuleTarget' from 'pdb'

### ISSUE THREAD

**Issue by nicovank** [plasma-umass/ChatDBG#16]
@ravenblood000 and I ran into issues installing chatDBG. Culprit seems to be f330919a4219b835128be740974e0fa1ec8e94fb, specifically [this line](https://github.com/plasma-umass/ChatDBG/blob/f330919a4219b835128be740974e0fa1ec8e94fb/src/chatdbg/chatdbg.py#L14). I suspect it works on your Python version but not other versions.

Reproduction.
```bash
% docker run -it ubuntu

% apt update
% apt install -y git python3 python3-pip
% git clone https://github.com/plasma-umass/ChatDBG.git
% cd ChatDBG
% python3 -m pip install --upgrade pip
% python3 -m pip install -e .
% python3 -m chatdbg

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/ChatDBG/src/chatdbg/__main__.py", line 3, in <module>
    from . import chatdbg
  File "/ChatDBG/src/chatdbg/chatdbg.py", line 14, in <module>
    from pdb import Pdb, Restart, _ModuleTarget, _ScriptTarget
ImportError: cannot import name '_ModuleTarget' from 'pdb' (/usr/lib/python3.10/pdb.py)
```

**Comment by nicovank** [comment]
Fixed.
